---
title: "Unit 7 Live Session: Comparing Two Groups"
output: 'pdf_document'  
classoption: landscape
fontsize: 12pt
---

# Class Announcements
- Great work completing your final w203 test!
- There is **no** unit 7 homework!
- The Hypothesis Testing Lab is released this week! 
    - The lab is due Tuesday 2pm of Week 09
    - Group lab in two parts: 
      - *Part 1*: Work as a team to engage the fundamentals of hypothesis tests
      - *Part 2*: Apply these fundamentals to analyze 2020 election data and write a single, three-page analysis
      
\newpage

## Working on Data Science Teams 

- Data science is a *beautiful* combination of team-work and individual-work
  - Teams:
    - Define research ambitions and scope
    - Imagine/envision the landscape of what is possible 
    - Support, discuss, review and integrate individual contributions
  - Individuals: 
    - Conduct the heads-down work that moves question answering forward 

\newpage

## What Makes an Effective Team?

- In 2012, Google researchers began a study to examine what makes teams effective. It was called [**Project Aristotle**](https://rework.withgoogle.com/print/guides/5721312655835136/).

> *Using input from executives across the globe, the research team identified 180 teams to study (115 project teams in engineering and 65 pods in sales) which included a mix of high- and low-performing teams. The study tested how both team composition (e.g., personality traits, sales skills, demographics on the team) and team dynamics (e.g., what it was like to work with teammates) impact team effectiveness.*

> *The researchers found that what really mattered was less about who is on the team, and more about how the team worked together.*

> *Of the five key dynamics of effective teams that the researchers identified, psychological safety was by far the most important. *

### Psychological safety: 

> *Psychological safety refers to an individual’s perception of the consequences of taking an interpersonal risk or a belief that a team is safe for risk taking in the face of being seen as ignorant, incompetent, negative, or disruptive. In a team with high psychological safety, teammates feel safe to take risks around their team members. They feel confident that no one on the team will embarrass or punish anyone else for admitting a mistake, asking a question, or offering a new idea.*

> *To measure a team’s level of psychological safety, Edmondson asked team members how strongly they agreed or disagreed with these statements:*

> - *If you make a mistake on this team, it is often held against you.*
> - *Members of this team are able to bring up problems and tough issues.*
> - *People on this team sometimes reject others for being different.*
> - *It is safe to take a risk on this team.*
> - *It is difficult to ask other members of this team for help.*
> - *No one on this team would deliberately act in a way that undermines my efforts.*
> - *Working with members of this team, my unique skills and talents are valued and utilized.*

## Discussion Questions

- From your experience, can you give an example of taking a personal risk as part of a team?
    - Can you describe your emotions when contemplating this risk?
    - If you did take the risk, how did the reactions of your teammates affect you?

- How can you add to the psychological safety of your peers in the section and lab teammates?


\newpage


# Roadmap
## Rearview Mirror
- Statisticians create a population model to represent the world
- A population model has parameters we are interested in
    - Ex: A parameter might represent the effect that a vitamin has on test performance
- A null hypothesis is a specific statement about a parameter
    - Ex: The vitamin has zero effect on performance
- A hypothesis test is a procedure for rejecting or not rejecting a null, such the probability of a type 1 error is constrained.

## Today
- There are often multiple hypothesis tests you can apply to a scenario.
- Our primary concern is choosing a test with assumptions we can defend.
- Secondarily, we want to maximize power.

## Looking Ahead
- Next week, we start working with models for linear regression
- We will see how hypothesis testing is also used for regression parameters.

\newpage
## Review of Key Terms

- Define each of the following:
    - Population Parameter
    - Null Hypothesis
    - Test Statistic
    - Null Distribution

## Comparing Groups Review

Take a moment to recall the tests you learned this week.  Here is a quick cheat-sheet to their key assumptions.

\begin{tabular}{l|p{50mm}|p{50mm}}
 & parametric  & non-parametric \\
 \hline
 unpaired & \textbf{unpaired t-test}  \newline metric var \newline  i.i.d. \newline (not too un-)normal)  & \textbf{Wicoxon rank-sum}  \newline ordinal var \newline i.i.d.)  \\
&&\\
 paired   & \textbf{paired t-test}  \newline metric var \newline  i.i.d.  \newline (not too un-)normal)  & \textbf{Wicoxon signed-rank}  \newline metric var \newline i.i.d. \newline difference is symmetric)   \newline  \newline OR \textbf{sign test}  \newline ordinal var \newline i.i.d.) 
\end{tabular}
   
\newpage   
# Comparing Groups R Exercise

The General Social Survey (GSS) is one of the longest running and extensive survey projects in the US.  The full dataset includes over 1000 variables spanning demographics, attitudes, and behaviors.  The file `GSS_w203.RData` contains a small selection of a variables from the 2018 GSS.  

To learn about each variable, you can enter it into the search bar at the [GSS data explorer](https://gssdataexplorer.norc.org/variables/vfilter)
    
```{r}
load('GSS_w203.RData')
summary(GSS)
```

You have a set of questions that you would like to answer with a statistical test. **For each question**:

1. Choose the most appropriate test.
2. List and evaluate the assumptions for your test.
3. Conduct your test.
4. Discuss statistical and practical significance.

## The Questions

- Do Americans with pets watch more or less TV than Americans without pets?
- Do economics majors watch more or less tv than computer science majors?
- Are Americans that own guns or Americans that don't own guns more likely to have pets?
- Do Americans spend more time emailing or using the web?
- Are Americans with pets happier than Americans without pets?
- Do Americans spend more evenings with neighbors or with relatives?